import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

import type { KhataTransaction, Person } from '@/types/app';
import { formatCurrency } from '@/utils/currency';
import { formatDisplayDate } from '@/utils/date';
import { getPersonBalance } from '@/utils/khata';

function escapeHtml(value: string) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

export async function sharePersonReportPdf(
  person: Person,
  transactions: KhataTransaction[],
  reportOwnerName?: string
) {
  if (!(await Sharing.isAvailableAsync())) {
    throw new Error('Sharing is not available on this device.');
  }

  const balance = getPersonBalance(person.id, transactions);
  const summaryLabel = person.isExpenseCategory
    ? 'Total expense'
    : balance < 0
      ? 'You paid advance'
      : balance > 0
        ? 'You have to pay'
        : 'Settled';
  const summaryColor = person.isExpenseCategory
    ? '#c43d3d'
    : balance < 0
      ? '#0f8a43'
      : balance > 0
        ? '#c43d3d'
        : '#102a24';

  const rows = [...transactions]
    .sort((first, second) => new Date(first.date).getTime() - new Date(second.date).getTime())
    .map((transaction, index) => {
      const customerTypeLabel = person.isExpenseCategory
        ? transaction.type === 'given'
          ? 'Paid'
          : 'Received'
        : transaction.type === 'given'
          ? 'You received'
          : 'You paid';
      const amountClass = person.isExpenseCategory
        ? transaction.type === 'given'
          ? 'amount paid'
          : 'amount received'
        : transaction.type === 'given'
          ? 'amount received'
          : 'amount paid';

      return `
        <tr>
          <td>${index + 1}</td>
          <td>${escapeHtml(formatDisplayDate(transaction.date))}</td>
          <td>${escapeHtml(customerTypeLabel)}</td>
          <td>${escapeHtml(transaction.note ?? '-')}</td>
          <td class="${amountClass}">${escapeHtml(formatCurrency(transaction.amount))}</td>
        </tr>
      `;
    })
    .join('');

  const html = `
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; padding: 28px; color: #102a24; }
          .title { font-size: 28px; font-weight: 700; margin: 0 0 6px; }
          .subtitle { font-size: 13px; color: #59706a; margin: 0 0 18px; }
          .summary { border: 1px solid #d8e4de; border-radius: 16px; padding: 16px; margin-bottom: 20px; background: #f7faf8; }
          .summary-label { font-size: 13px; color: #59706a; margin-bottom: 6px; }
          .summary-value { font-size: 24px; font-weight: 800; color: ${summaryColor}; }
          table { width: 100%; border-collapse: collapse; font-size: 13px; }
          th, td { border: 1px solid #d8e4de; padding: 10px; text-align: left; vertical-align: top; }
          th { background: #edf3ef; }
          .amount { text-align: right; white-space: nowrap; }
          .amount.received { color: #0f8a43; font-weight: 700; }
          .amount.paid { color: #c43d3d; font-weight: 700; }
          .footer { margin-top: 14px; font-size: 12px; color: #59706a; }
        </style>
      </head>
      <body>
        <h1 class="title">${escapeHtml(person.name)}</h1>
        <p class="subtitle">${escapeHtml(
          person.isExpenseCategory
            ? 'Expense category report'
            : person.phoneNumber || 'Khata statement from your point of view'
        )}</p>
        <div class="summary">
          <div class="summary-label">${escapeHtml(summaryLabel)}</div>
          <div class="summary-value">${escapeHtml(formatCurrency(Math.abs(balance)))}</div>
        </div>
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Date</th>
              <th>Type</th>
              <th>Note</th>
              <th class="amount">Amount</th>
            </tr>
          </thead>
          <tbody>
            ${rows || '<tr><td colspan="5">No transactions available.</td></tr>'}
          </tbody>
        </table>
        <div class="footer">Generated by ${escapeHtml(reportOwnerName?.trim() || 'My Khata')}</div>
      </body>
    </html>
  `;

  const file = await Print.printToFileAsync({ html });

  await Sharing.shareAsync(file.uri, {
    mimeType: 'application/pdf',
    dialogTitle: 'Share khata report',
    UTI: 'com.adobe.pdf',
  });
}
